// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOGM0wbnffJ3c4ZkzY6FhOswzVeDvV7Ys',
    appId: '1:744253652613:web:724f898d0a955a90c873ec',
    messagingSenderId: '744253652613',
    projectId: 'handinhandup',
    authDomain: 'handinhandup.firebaseapp.com',
    storageBucket: 'handinhandup.appspot.com',
    measurementId: 'G-9EDTGPFPCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPMV9RAooU-VM5d6uNbqN3vXaKHyszBmQ',
    appId: '1:744253652613:android:71e37d088690f856c873ec',
    messagingSenderId: '744253652613',
    projectId: 'handinhandup',
    storageBucket: 'handinhandup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0qXJMJ_fs_3eo1bWPDGtPwn_ma9hw_G4',
    appId: '1:744253652613:ios:e4e896ce43337987c873ec',
    messagingSenderId: '744253652613',
    projectId: 'handinhandup',
    storageBucket: 'handinhandup.appspot.com',
    iosBundleId: 'com.example.handinhandup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0qXJMJ_fs_3eo1bWPDGtPwn_ma9hw_G4',
    appId: '1:744253652613:ios:cf876b1fd93ede87c873ec',
    messagingSenderId: '744253652613',
    projectId: 'handinhandup',
    storageBucket: 'handinhandup.appspot.com',
    iosBundleId: 'com.example.handinhandup.RunnerTests',
  );
}
